### ISSUE TITLE
Colab link missing

### ISSUE THREAD

**Issue by stefan-apollo** [callummcdougall/sae_visualizer#1]
The "[Colab](https://github.com/callummcdougall/sae_visualizer/blob/main)" link points to this GitHub, do you have a Google Colab link somewhere?

> You can use my [Colab](https://github.com/callummcdougall/sae_visualizer/blob/main) to generate more of these visualisations. You can use this [sae visualiser](https://www.perfectlynormal.co.uk/blog-sae) to navigate through the first thousand features of the aforementioned autoencoder.

**Comment by callummcdougall** [comment]
Ah thanks, I'll fix this (although I'll note that the new updated repo can be found [here](https://github.com/callummcdougall/sae_vis), I'd recommend using that from now on, it's better documented and has more features. Will be making a post about it this week.)
